### PR TITLE
Include repo url in committime

### LINKED ISSUE #1089: commit_timestamp should include source repo URLs so that users can audit/understand/validate measure calculation
### Feature description

Currently the commit timestamp metric looks like this:

```
commit_timestamp{app="/pelorus-api/", commit="159c63792a5c1b0d34902be8bc2280406ad1ef06", image_sha="sha256:fad7883875aadddd22bcc7d5c03ac581be84795205dbf412c8c1253342b6ee71"}
```

In order to be able to trace the commit back to the source, I would like commit timestamp to also include the repo URL OR the commit URL, like this:

```
commit_timestamp{app="/pelorus-api/", commit="159c63792a5c1b0d34902be8bc2280406ad1ef06", image_sha="sha256:fad7883875aadddd22bcc7d5c03ac581be84795205dbf412c8c1253342b6ee71", repo_url="https://github.com/etsauer/pelorus-api"}
```

OR

```
commit_timestamp{app="/pelorus-api/", commit="159c63792a5c1b0d34902be8bc2280406ad1ef06", image_sha="sha256:fad7883875aadddd22bcc7d5c03ac581be84795205dbf412c8c1253342b6ee71", commit_url="https://github.com/etsauer/pelorus-api/commit/159c63792a5c1b0d34902be8bc2280406ad1ef06"}
```

### How this will help you

This will greatly improve the quality and integrity of the results that we show to users.

### Feature priority

⌛ It will greatly improve my experience using Pelorus

### Code of Conduct

- [X] I agree to follow Pelorus's Code of Conduct

### PR DESCRIPTION
**Pull request by etsauer**
- [x] I have read [Pelorus Contributing guidelines](https://github.com/dora-metrics/pelorus/blob/master/CONTRIBUTING.md)

## Linked Issues

resolves #1089 

## Description

This change adds a new `repo_url` label to the committime metric across all providers. It ensures that when we capture a commit time, we also capture the source code repo URL for that commit. This will help us to show users where their metrics are coming from and help users validate the metrics we collect when there are questions about how we're getting our data.

## Testing Instructions

Deploy the operator from the PR builds above.

Set up a pelorus instance with the following comittime exporter types:

```
      - enabled: true
        app_name: committime-image
        exporter_type: committime
        extraEnv:
        - name: PROVIDER
          value: containerimage
      - enabled: true
        app_name: committime-git
        exporter_type: committime
        extraEnv:
        - name: PROVIDER
          value: git

```

Generate data by running through the examples here: https://pelorus.readthedocs.io/en/v2.0.12/GettingStarted/configuration/ExporterCommittime/#example-workflow-for-an-openshift-binary-build

Check in Prometheus for `commit_timestamp` entries. You should now see metrics that look like this:

```
commit_timestamp{app="/pelorus-api/", commit="fefa7416e2c3ee424f53dbdbd46b7b758da4eb3d", container="committime-exporter", endpoint="http", exported_namespace="pelorus-api", image_sha="sha256:90f5978f8aa4303aacb4eb997a7e15371222515bc67300db1d5ab13b1296b335", instance="10.128.1.56:8080", job="committime-exporter", namespace="test-pelorus-operator", pod="committime-exporter-1-v2ktw", repo_url="https://github.com/etsauer/pelorus-api", service="committime-exporter"} | 1717780394
-- | --
commit_timestamp{app="/python-binary-build/", commit="7810f2a85d5c89cb4b17e9a3208a311af65338d8", container="committime-exporter-git", endpoint="http", exported_namespace="binary-build", image_sha="sha256:71a1f49ff412b13ef2d3e4663d890892ff99b66fe841679e26c2350ccd2bd5f5", instance="10.128.1.68:8080", job="committime-exporter-git", namespace="test-pelorus-operator", pod="committime-exporter-git-1-9jjhw", repo_url="http://github.com/dora-metrics/pelorus", service="committime-exporter-git"} | 1654810223

```

### CODE REVIEW

**Comment by etsauer** [comment]
@mpryc @weshayutin @mateusoliveira43 @KevinMGranger thinking about this a bit more... I think what would be more useful than just the repo url would be the direct link to the commit (e.g. https://github.com/dora-metrics/pelorus/commit/7810f2a85d5c89cb4b17e9a3208a311af65338d8). This information looks to be provided in the api response we get back from the git providers already, so it would be easy to extract. The question is, where do "store" it. Do we add a new field to CommitMetric for a "commit_link"? do we overload "repo_url" in some way? Thoughts?

**Comment by etsauer** [comment]
I started going down this path today, and hit a little snag. https://github.com/dora-metrics/pelorus/blob/master/exporters/committime/collector_base.py#L396-L398

It looks as if today, we ONLY cache the commit_timestamp rather than the entire metric. As a result, on exporter start, we get the correct metric the first time, as it is not yet cached, and calls out to github, but on scrape, the metric appears cached, but information is missing.

 Are we open to changing this?

**Review by mpryc — COMMENTED** [review]
Is it possible to update documentation as well? It will be out of sync once this is merged?

It can be in separate PR, but I would like to know what is the plan for that.

**Comment by mpryc** [comment]
Secondly the Prometheus Rules Test did fail, but that's not this PR introduction, however I am more worried about Mockoon test.

**Review by cgruver — APPROVED** [review]

**Pull request merged**
