### PR TITLE
Enhance e2e script test to cover webhook exporter

### LINKED ISSUE #858: Cover Webhook Exporter in our e2e tests
Our Webhook Exporter have pretty solid unit tests written, but we should extend our e2e tests to cover it's functionality.

For more information please see the relevant PRs: https://github.com/konveyor/pelorus/pull/844 https://github.com/konveyor/pelorus/pull/836

Features:
- end to end (e2e) tests of webhook exporter

Requirements:
- [ ] Prow
  - [x] It should be triggered similar to other e2e tests (PRs and periodic) 
  - [x] Add webhook test
  - [ ] Tests should cover
    - [x] deployment of webhook exporter
    - [ ] sending sample data [commitime, deploytiume, ...]
    - [x] verifying the data was received

### PR DESCRIPTION
**Pull request by mpryc**
Enables webhook exporter with and without secret
in our e2e tests.

Fixes #858

Depends on: https://github.com/konveyor/mig-demo-apps/pull/101

Test command examples:
```
# Both webhook without and with secret exporters
$ ./scripts/run-pelorus-e2e-tests.sh -e webhook,webhook_with_secret

# Just webhook without SECRET option
$ ./scripts/run-pelorus-e2e-tests.sh -e webhook

# Just webhook with SECRET option
$ ./scripts/run-pelorus-e2e-tests.sh -e webhook_with_secret

```

### CODE REVIEW

**Review by mateusoliveira43 — CHANGES_REQUESTED** [review]
just rebase to fix conflicts and add test command to PR description after merging PR in mig-demo-apps (already approved it)

**Comment by mateusoliveira43** [comment]
tested with `./scripts/run-pelorus-e2e-tests.sh -e webhook,webhook_with_secret`, it worked

looking into the issue description, should more data be send? (one of each metric type)

**Review by mateusoliveira43 — APPROVED** [review]

**Review by mateusoliveira43 — CHANGES_REQUESTED** [review]
update docs (never mind, this does not apply to webhook (yet))

**Review by mateusoliveira43 — APPROVED** [review]

**Comment by mpryc** [comment]
> update docs (never mind, this does not apply to webhook (yet))

I don't see any place where we explicitly enable/disable particular exporters. In the docs/Development.md we mention `./scripts/run-pelorus-e2e-tests.sh -h` so this should present those two exporters to be enabled. Makefile enables all of them, so I am not sure what you are asking here.

**Comment by mateusoliveira43** [comment]
I was thinking about this part https://pelorus.readthedocs.io/en/latest/UpstreamSupport/#committime-exporter

**Pull request merged**
