### PR TITLE
fix: Azure devops e2e test

### LINKED ISSUE #569: CI: Azure Devops commit exporter
TO-DO create CI for Backend

### LINKED ISSUE #899: Azure devops e2e tests
### Fix
Azure devops is not being tested by our end to end (e2e) tests.

### Requirements
- [x] Create development account on Azure devops
- [x] write e2e tests (also unit and integration, if possible)
- [x] add credentials to Prow
- [x] Add Azure devops e2e tests to CI
- [x] Document new environment variable needed to run `make e2e-tests`

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Describe the behavior changes introduced in this PR

Add Azure devops end to end (e2e) tests to project CI.

## Linked Issues

resolves #899
resolves #569

## Testing Instructions

- [x] Update e2e script after #912 is merged
- [x] Update command after `konveyor/mig-demo-apps` PR is merged

To run end to end tests with Azure devops, run
```
export AZURE_DEVOPS_TOKEN=YOUR_AZURE_DEVOPS_TOKEN
./scripts/run-pelorus-e2e-tests -e azure-devops-committime
```

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
/hold

@weshayutin we need to add secret to Prow before closing this one

**Review by mpryc — APPROVED** [review]

**Pull request merged**
