### PR TITLE
fix: PagerDuty e2e test

### LINKED ISSUE #880: CI e2e PagerDuty exporter
Features:
- Add end to end (e2e) tests for PagerDuty exporter.

Requirements:
  - [x] Create development account on PagerDuty
  - [x] write e2e tests
  - [x] Add credentials to Prow
  - [x] Add PagerDuty e2e tests to CI
  - [x] Document new environment variable needed to run `make e2e-tests`

### PR DESCRIPTION
**Pull request by mateusoliveira43**
## Describe the behavior changes introduced in this PR

Fix PagerDuty end to end (e2e) tests.

## Linked Issues

resolves #880

## Testing Instructions

- [x] Update command after PR in `konveyor/mig-demo-apps` is merged

To run end to end tests with PagerDuty, run
```
export PAGER_DUTY_TOKEN=YOUR_TOKEN
./scripts/run-pelorus-e2e-tests -e pagerduty_failure
```

To clean the environment afterwards, run
```
curl https://raw.githubusercontent.com/konveyor/mig-demo-apps/master/apps/todolist-mongo-go/mongo-persistent.yaml | oc delete -f -
helm uninstall pelorus --namespace pelorus
helm uninstall operators --namespace pelorus
```

### CODE REVIEW

**Comment by mateusoliveira43** [comment]
/hold 

@weshayutin we need to add secret to Prow before closing this one

**Review by mpryc — APPROVED** [review]

**Pull request merged**
